export const DATEPICKER_INPUT_DATE_FORMAT = 'dd/MM/yyyy'

export const DEFAULT_DATE_FORMAT = 'DD/MM/YYYY'
export const QUERY_PARAM_DATE_FORMAT = 'DD-MM-YYYY'
export const CELL_DATE_FORMAT = 'DD MMMM YYYY'
